export default {
  title: 'light',
  media: {
    lteMedium: '(max-width: 768px)',
    lteOrEqSmallest: '(max-width: 320px)',
    lteOrEqSmall: '(max-width: 576px)',
    lteOrEqMedium: '(max-width: 768px)',
    lteOrEqLarge: '(max-width: 992px)',
    gteOrEqSmallest: '(min-width: 320px)',
    gteOrEqSmall: '(min-width: 576px)',
    gteOrEqMedium: '(min-width: 768px)',
    gteOrEqLarge: '(min-width: 992px)',
  },
  bg: {
    primary: '#007',
    secondary: '#6c757d',
    success: '#28a745',
    danger: '#dc3545',
    warning: '#ffc',
    info: '#2ab5fa',
    body: '#f8f9fa',
    default: '#f8f9fa',
    dark: '#343a40',
    light: '#ffffff',
  },
  fg: {
    primary: '#007',
    secondary: '#6c757d',
    success: '#28a745',
    danger: '#dc3545',
    warning: '#ffc',
    info: '#2ab5fa',
    body: '#343a40',
    default: '#343a40',
    dark: '#343a40',
    light: '#f8f9fa',
  },
}
